name: musa-620
channels:
  - defaults
  - conda-forge
  - pyviz
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - cartopy
  - altair
  - vega_datasets
  - notebook
  - vega
  - seaborn
  - hvplot
  - geoviews
  - requests
  - pip:
      - carto
      - pyrestcli
